2017/09/08 00:31
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 202, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 21, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

2017/09/07 23:56
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 201, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 21, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

2017/09/07 23:55
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 201, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 22, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

2017/09/07 23:50
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 201, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 22, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

2017/09/07 23:50
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 201, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 22, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

2017/09/07 23:50
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 201, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 22, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

2017/09/07 23:49
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 201, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 22, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

2017/09/07 22:21
QFn.fn.man
Traceback (most recent call last):
  File "D:\QFn\QFn\function.py", line 183, in __call__
    self.fn(**kwargs)
  File "D:\QFn\QFn\fn.py", line 21, in man
    print "三维：", body[0], body[1], body[2]
TypeError: 'int' object has no attribute '__getitem__'

